appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: G9KbMYhVpzGadcuxJvfzm7g6I316ooJcFF7HWIDJTo8JP+3ObOgmsj56bdOzlofs7/aHZkyLaKUl4djbyiNW8VvMY3kwKsNkg1Lwq8l+8Ug2pNOh9+3E6CkFcd0PgIR7sb5WtHpUmxpXusq5ZzuCltcLAbpv7n4zBvVBTi0ymdyNBrTn5pL8ec1OVXIAhQII+T3uCgq5CNfelXvVZ6MsZ4k+dR8yUTkRiexABumGYsoUK1MhgI15yyRczCvvwbHLFB5IBWWjp5tEGXK0iulMIhFvl9sfnnHZ3XIGfeOozO2VxfX2PZKK7/a33e39LYzH/i9MzkAD/QIhcDjm1B8fexwkGxgNAmyusL31eqEjpFIMzampLT5K8/ncNwcXMLMyHli+Tds7eZDzbmjbh59vxGSBKt1CsHcggr6C2jxdzNTxk0v86kOsAgdT5cpRQVI8D5zDxzvi9/S0rDeJxbuh579oCJCXZJTuvdwOfarVKuw4/HbxDhZ21AymkyB0N3N6K9K0br39pdi5VHLE6kCn+bCLY3xJXD9XDSysy2dL2anNu7gs2375GIPyTVqWTEkmj41hksY7cZNCZWTzCg16pxZRsTVSxdGaq1wk18MWo8HgIQnLfhCImM0O4yaTAk3Ef4wBLSuW7pYu7nd5ed9ulBIXS3QDDc5WrgWNxKnJCmI=}
bot:
  automerge: true
